---

- name: Create a directory for static files
  become: yes
  become_method: sudo
  file:
    path: /srv/STATIC_FILES
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775

- name: Execute manage.py collectstatic
  shell: /srv/VENVs/django-polls/bin/python manage.py collectstatic --noinput
  args:
    chdir: "{{ local_repo_path }}"


