---

- name: Directory to store VENVs
  become: yes
  become_method: sudo
  file:
    path: "{{ virtualenv_root }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775

#- name: Manually create the initial virtualenv
#  command: /opt/python3-altinstall/bin/python3.5 -m venv django-polls
#  args:
#    chdir: "{{ virtualenv_root }}"
#    creates: "{{ virtualenv_root }}/django-polls"

- name: Install requirements.txt
  pip:
    chdir: "{{ local_repo_path }}"
    requirements: requirements.txt
    virtualenv: "{{ virtualenv_root }}/django-polls"

