---

- hosts: webappservers
  become: yes
  become_method: sudo

  tasks:

  - name: Install EPEL repository
    yum:
      name: epel-release
      state: installed

  - name: Install nginx
    yum:
      name: nginx
      state: installed

  - name: Copy over nginx.conf
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: Restart nginx

  - name: Copy over webapp content
    template:
      src: index.html.j2
      dest: /usr/share/nginx/html/index.html
    notify: Restart nginx

  handlers:

  - name: Restart nginx
    service:
      name: nginx
      state: restarted

#############################################################
#############################################################

- hosts: loadbalancers
  become: yes
  become_method: sudo

  tasks:

  - name: Install haproxy and socat
    yum: name="{{ item }}" state=installed
    with_items:
      - haproxy
      - socat

  - name: Copy over haproxy.cfg
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: Restart haproxy

  handlers:

  - name: Restart haproxy
    service:
      name: haproxy
      state: restarted

